config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  get 'pages/home'

  get 'pages/bookbox'

  get 'pages/contact'

  resources :contributions

end

app/models/contribution.rb
class Contribution < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController
  def new
    @contribution = Contribution.new
  end

  def create
    @contribution = Contribution.new(contribution_params)
    @contribution.save
    redirect_to contributions_path
  end

  def destroy
    @contribution = Contribution.find(params[:id])
    @contribution.destroy
    redirect_to contributions_path
  end

  def index
    @contributions = Contribution.all
  end

  private

  def contribution_params
    params.require(:contribution).permit(:name, :strophe)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def bookbox
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contributions_helper.rb
module ContributionsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contributions/_contribution_form.html.erb
<%= simple_form_for(@contribution) do |f| %>
  <%= f.error_notification %>

  <%= f.input :name, label: 'Prénom' %>
  <%= f.input :strophe, as: :text %>

  <%= f.button :submit %>
<% end %>

app/views/contributions/index.html.erb
<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <link rel="stylesheet" type="text/css" href="style.css">

  <title>La Rose de Ronsard</title>

  <!-- Bootstrap -->
  <link href="css/bootstrap.min.css" rel="stylesheet">

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
      <![endif]-->
    </head>
    <body>

        <ul class="nav">
          <li><%= link_to 'La Rose de Ronsard', pages_home_path %></li>
          <li><%= link_to 'Bookboxes', pages_bookbox_path %></li>
          <li><%= link_to 'Contact', pages_contact_path %></li>
          <li><%= link_to 'La nouvelle Rose', contributions_path %></li>
        </ul></div>


        <div id="article">
           <h1>Mignonne, allons voir si la rose</h1>
           <br>
           <p class="last">
            A Cassandre
            <br>
            <br>
            Mignonne, allons voir si la rose<br>Qui ce matin avoit desclose<br>
            ...
            <br>
            <br>

            <% @contributions.each do |c| %>
            <ul>
             <i class="fa fa-quote-right" style="color:black;" aria-hidden="true"></i>
             <li font face= 12px/20px "Helvetica Neue", "Arial", "Helvetica"> <%= c.strophe %> </li>
             <li font face= 12px/20px "Helvetica Neue", "Arial", "Helvetica"><strong> <%= c.name %> </strong></li>
           </ul>

           <%= link_to "delete", contribution_path(c.id), method: :delete %>

           <% end %>
           <br>
           <br>
           <p font face= 12px/20px "Helvetica Neue", "Arial", "Helvetica">
             <strong> Le Poème vit et vivra grâce à vous,<br> n'hésitez pas à rajouter une ligne ou une strophe :</strong>   <br><br> <%= link_to 'Ajouter une strophe', new_contribution_path %> <br><br>
           </p>

           <br>

        </div>



    </body>
    </html>

app/views/contributions/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-4 col-offset-4">
      <h1> Ajoutez votre grain de sel</h1>
        <%= render 'contribution_form' %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>TODO</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/bookbox.html.erb
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
     <link rel="stylesheet" type="text/css" href="style.css">

    <title>La Rose de Ronsard</title>


  </head>
  <body>
   <div>

<ul class="nav">
  <li><%= link_to 'La Rose de Ronsard', pages_home_path %></li>
  <li><%= link_to 'Bookboxes', pages_bookbox_path %></li>
  <li><%= link_to 'Contact', pages_contact_path %></li>
  <li><%= link_to 'La nouvelle Rose', contributions_path %></li>
</ul></div>
 <div id="article">
 <font color="#7a7a7a">
 <i>Qui que vous soyez qui voulez cultiver, vivifier, édifier, attendrir, apaiser :<br>
  mettez des livres partout.</i> Victor Hugo
 <br> <br>


</font>
<%= image_tag 'a.jpg'%>
<%= image_tag 'b.jpg'%>
<%= image_tag 'c.jpg'%>
<%= image_tag 'd.jpg'%>
<br>
<%= image_tag 'e.jpg'%>
<%= image_tag 'f.jpg'%>
<%= image_tag 'g.jpg'%>
<%= image_tag 'h.jpg'%>
<br><br><br>
            </div>


<br>


 </div>


    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
  </body>
</html>

app/views/pages/contact.html.erb
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
     <link rel="stylesheet" type="text/css" href="style.css">

    <title>Contact</title>

  </head>
  <body>
  <div>

<ul class="nav">
  <li><%= link_to 'La Rose de Ronsard', pages_home_path %></li>
  <li><%= link_to 'Bookboxes', pages_bookbox_path %></li>
  <li><%= link_to 'Contact', pages_contact_path %></li>
  <li><%= link_to 'La nouvelle Rose', contributions_path %></li>
</ul></div>

 <div id="article">

            <font color="#7a7a7a">
  <H1>Contact</H1>
  For more information, please contact me on:
  </font><br><br>



 <a href="mailto:valentine@smets.lu"><%= image_tag 'mail.png', :style => "width: 100px; height:100px; margin-right: 50px;"%></a>



<a href="https://www.facebook.com/valsmets?fref=ts"><%= image_tag 'face.png', :style => "width: 80px; height:80px; margin-right: 80px;"%></a>



<a href="https://www.instagram.com/val_smets/  "><%= image_tag 'insta.png', :style => "width: 80px; height:80px"%></a>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br>

            </div>





 </div>


    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
  </body>
</html>

app/views/pages/home.html.erb
<!doctype html>
<HTML lang="FR">
<HEAD>
<link rel="stylesheet" type="text/css" href="style.css">
<meta charset="UTF-8">
<TITLE></TITLE>
</HEAD>
 <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Bootstrap 101 Template</title>

    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body >
<div class="container">
<div>

<ul class="nav">
  <li><%= link_to 'La Rose de Ronsard', pages_home_path %></li>
  <li><%= link_to 'Bookboxes', pages_bookbox_path %></li>
  <li><%= link_to 'Contact', pages_contact_path %></li>
  <li><%= link_to 'La nouvelle Rose', contributions_path %></li>
</ul></div>

<div id="article">
<h1>Mignonne, allons voir si la rose</h1>

            <p class="last">
            A Cassandre
            <br>
            <br>
            Mignonne, allons voir si la rose<br>Qui ce matin avoit desclose<br>Sa robe de pourpre au Soleil,<br>A point perdu ceste vesprée<br>Les plis de sa robe pourprée,<br>Et son teint au vostre pareil.<br><br>Las ! voyez comme en peu d'espace,<br>Mignonne, elle a dessus la place<br>Las ! las ses beautez laissé cheoir !<br>Ô vrayment marastre Nature,<br>Puis qu'une telle fleur ne dure<br>Que du matin jusques au soir !<br><br>Donc, si vous me croyez, mignonne,<br>Tandis que vostre âge fleuronne<br>En sa plus verte nouveauté,<br>Cueillez, cueillez vostre jeunesse :<br>Comme à ceste fleur la vieillesse<br>Fera ternir vostre beauté.</p>
            <br>
            <strong>Pierre de RONSARD</strong>  (1524-1585)<br>
            <br><br>


</div>


</div>

</BODY>
</HTML>

app/views/shared/_footer.html.erb
<div class="footer">
  Valentine Smets
</div>